[profile.default]
solc = "0.8.19"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
#optimizer-runs = 10_000_000

remappings = [
    "@ethereum-attestation-service/eas-contracts/contracts/=node_modules/@ethereum-attestation-service/eas-contracts/contracts/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/",
    "forge-std/=lib/forge-std/src/",
    "murky/=lib/murky/src/"
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config